### PR TITLE
fix add else statements for kevins remove (closes #27)

### LINKED ISSUE #27: fix: Add else-statements for Kevins remove
Forgot to add else statements to remove method in branch controll according to instructions

### PR DESCRIPTION
**Pull request by KevinLov**
Adding else clasuses to if statements

### CODE REVIEW

File: src/main/java/org/apache/commons/collections4/map/Flat3Map.java [hunk 1]
```diff
@@ -1225,11 +1247,15 @@ public V remove(final Object key) {
...
                     size = 0;
                     return old;
+                } else {
+                    Coverage.hit(137);
                 }
-                Coverage.hit(137);
             }
+        } else {
+            Coverage.hit(107);
+            return null;
```
Comment (Eggetxd) [inline src/main/java/org/apache/commons/collections4/map/Flat3Map.java]: dont think this changes anything really but I don't think we should add return while we add Coverage.hit()

**Comment by samuelpeetre** [comment]
LGTM
